name: Docs
on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  build-and-deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Clean install
        run: npm ci
      - name: Build
        run: npm run build-storybook
      - name: No Jekyll
        run: touch ./docs/.nojekyll
      - name: Build and deploy to storybook-static branch
        uses: JamesIves/github-pages-deploy-action@v4.6.0
        with:
          folder: docs # The folder the action should deploy.
          branch: docs
